spring:
  application:
    name: product
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/sparta?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

---

spring:
  application:
    name: product
  profiles:
    active: prod
  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: prod-redis.example.com
      port: 6379
      username: default
      password: prod_redis_pass
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone:

management:
  zipkin:
    tracing:
      endpoint: "http://zipkin.prod.example.com/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0