spring:
  application:
    name: product
  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host:
      port: 6379
      username: default
      password: systempass

server:
  port:

eureka:
  client:
    service-url:
      defaultZone:


management:
  zipkin:
    tracing:
      endpoint:
  tracing:
    sampling:
      probability: 1.0
