server:
  port: 19091  # ????? ???? ??? ?? ??

spring:
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  application:
    name: gateway  # ?????? ??? 'gateway-service'? ??
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway? ??? ??
        - id: order  # ??? ???
          uri: lb://order  # 'order-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/orders/**  # /order/** ??? ???? ??? ? ???? ??
        - id: product  # ??? ???
          uri: lb://product  # 'product-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/products/**  # /product/** ??? ???? ??? ? ???? ??
        - id: auth-service  # ??? ???
          uri: lb://auth-service  # 'auth-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/auth/signIn  # /auth/signIn ??? ???? ??? ? ???? ??
      discovery:
        locator:
          enabled: true  # ??? ?????? ?? ???? ???? ????? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"


